[server]
end-point-enable-batch-if-possible = false
## Listening address.
addr = "127.0.0.1:12306"
status-addr = ""

[pd]
endpoints = ["127.0.0.1:3379"]

[storage]
data-dir = "/tmp/copr_test/tikv_no_batch"

[rocksdb]
max-open-files = 64

[raftdb]
max-open-files = 64
